- name: Settingup cart Server
  hosts: cart
  become: yes
  tasks:
    - name: Disableing Old Nodejs & Enabeling Nodejs18
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

    - name: Instaling Nodejs
      ansible.builtin.package:
        name: nodejs
        state: present 

    - name: Adding user roboshop
      ansible.builtin.user:
        name: roboshop
    
    - name: Ceeating Directory called App
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Donload cart Application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/cart.zip
        dest: /tmp

    - name: Extracting cart Application
      ansible.builtin.unarchive: 
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes #if file is alredy in remote source

    - name: Installing nmp Dependecies
      ansible.builtin.command: npm install
      args: #args can be used to change directory
        chdir: /app

    - name: Copying cart Service
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: Demon Reload
      ansible.builtin.systemd_service: 
        demon_reload: true

    - name: start and enable cart
      ansible.builtin.service:
        name: cart
        state: restarted
        enabled: yes
    