- name: Settingup Catalogue Server
  hosts: catalogue
  become: yes
  tasks:

    - name: Disableing Old Nodejs % Enabeling Nodejs18
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

    - name: Instaling Nodejs
      ansible.builtin.package:
        name: nodejs
        state: present 

    - name: Adding User roboshop
      ansible.builtin.user:
        name: roboshop
    
    - name: Recursively remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Creating Directory called App
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Donload Catalogue Application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp

    - name: Extracting Catalogue Application
      ansible.builtin.unarchive: 
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes #if file is alredy in remote source

    - name: Installing nmp Dependecies
      ansible.builtin.command: npm install
      args: #args can be used to change directory
        chdir: /app

    - name: Copying Catalogue Service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Daemon Reload
      ansible.builtin.systemd_service: 
        daemon_reload: true

    - name: Copying MongoDB
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo 
   
    - name: Installing MongoDB Client
      ansible.builtin.package:
        name: mongodb-org-shell
        state: present 

    - name: Get calatlogue count
      ansible.builtin.command:  mongo --host mongodb.projoy.store --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
      register: product_count

    # - name: print the count
    #   ansible.builtin.debug:
    #     msg: "product count: {{product_count}}"

    - name: load catalogue data
      ansible.builtin.command: mongo --host mongodb.projoy.store < /app/schema/catalogue.js
      when: product_count.stdout == "0"

    - name: start and enable catalogue
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: yes
    