- name: Settingup MongoDB Sevrver
  hosts: mongodb
  become: yes 
  tasks:
    - name: Copying MongoDB
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo 
    
    - name: Installing MongoDB
      ansible.builtin.package:
        name: mongodb-org
        state: present 

    - name: Enabling and Starting MongoDB Server
      ansible.builtin.service:
        name: mongod
        state: started
        enable: yes

    - name: Allowing Remote Connection
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '10.0.0.0'

    - name: Resrating MongoDB
      ansible.builtin.service:
        name: mongod
        state: restarted  
    
